# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 655ca1eadccd03dcc2beba5cc5ce2ab1e2182036738faab9ad2d6fd88277cc49ce5a25dbdbd679dbd6a39a02637eee2a339620e2d3f072c6a5139b1c38032baf

test:
  secret_key_base: 508b5acce7688b8ff6d6dbfe24092d32f7eec262dc9d14f2d406d0034e3b79fea2ce3be5798617efa79450bbeec94d2a1a3f64651d7e2e0997067dc05391862f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
